### PR TITLE
Hackbot giphy

### PR DESCRIPTION
**Pull request by paked**
This is the beginning of some **fun** *activities* in Hackbot.

It's pretty simple, and allows Hackbot to respond people with gifs as they request them 💃 

- [x] We're going to need to add a Giphy API key to Heroku before this gets merged.

### CODE REVIEW

**Comment by MaxWofford** [comment]
@paked What about something like `@hackbot gif`?

**Comment by MaxWofford** [comment]
Won't there be a space left over?

**Comment by paked** [comment]
@MaxWofford: I'm not quite sure what you're saying here?

**Comment by MaxWofford** [comment]
@paked What happens when you send the message `hackbot     gif`?

**Comment by MaxWofford** [comment]
Markdown is reformatting my messages. "@hackbot  . . . . .  gif" where the `.`s are whitespace.

**Comment by paked** [comment]
That's what the `.strip` on line #27 catches.

**Comment by MaxWofford** [comment]
@paked Ah, gotcha.

**Pull request merged**
