### PR TITLE
[WIP] Challenge post mailer

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by zachlatta** [comment]
Hey, can I help with this at all?

**Comment by zachlatta** [comment]
Would it still be helpful if I took a crack at this? Happy to do.

--
Zach Latta

https://zachlatta.com ( http://zachlatta.com )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://www.facebook.com/crynix ) / github ( https://github.com/zachlatta )

**Comment by lachlanjc** [comment]
Are we still doing this?

**Comment by MaxWofford** [comment]
Think it's safe to close this, feel free to reopen if anyone feels different

CC'ing @polytroper, as challenge is his domain

###### polytroper.challenge

**Comment by polytroper** [comment]
:+1:

**Pull request closed without merging**
