### PR TITLE
Use pagination for StreakClient::Box.all_in_pipeline

### PR DESCRIPTION
**Pull request by paked**
This PR changes the way in which `StreakClient::Box.all_in_pipeline` retrieves it's boxes. Previously it pulled down the entire pipeline at once through the v1 API, which *sometimes caused 500 errors* and was very slow. Now, we use pagination (ie. the v2 API).

This should be good to merge as it is, and not effect the performance of our application too much – but I do want to consider caching this function just to make everything as quick as possible.

If we do decide to cache, what would this look like? Caching the individual network requests seems like a bad idea prone to error. Does that mean we just cache at a function level?

Would love your thoughts @MaxWofford.

### CODE REVIEW

**Comment by paked** [comment]
FYI: Also in the middle of rewriting this to use an Enumerable.

**Comment by MaxWofford** [comment]
@paked could you ping me once you've rewritten it with Enumerables?

**Comment by paked** [comment]
@MaxWofford: ready to review.

**Comment by MaxWofford** [comment]
parrotmiddleparrotrightparrot

**Pull request merged**
