### PR TITLE
Fancy mailer ✉️

### PR DESCRIPTION
**Pull request by cjdenio**
Basically a copy of the new Bank mailer layout.

Screen Shot 2022-02-11 at 1 09 39 AM

### CODE REVIEW

**Comment by maxwofford** [comment]
@cjdenio This looks great! Can we merge it? Also, is there a way to show the bank logo on this (I'm cool with merging even if not)?

**Comment by cjdenio** [comment]
Oh yeah, I guess Bank is the only thing using this auth system now. Please stand by...

**Comment by maxwofford** [comment]
Let's leave the HC branding. it'd be cool to add something that lets bank ask for a different logo when sending bank signin emails, but i'd like to keep the API bank-agnostic still

**Comment by cjdenio** [comment]
All good to merge then!

**Pull request merged**
